from PyQt6 import QtCore, QtGui, QtWidgets
from pyvin import VIN
import customer_hub
import mysql.connector
from database.vehicles import vehicle_db

class Ui_Form(object):

    #### collect vin data
    def vin_search(self):
        try:
            self.vin = VIN(self.vin_line.text())
            self.year_line.setText(self.vin.ModelYear)
            self.make_line.setText(self.vin.Make)
            self.model_line.setText(self.vin.Model)
            self.engine_line.setText(self.vin.DisplacementL)
            self.trim_line.setText(self.vin.Trim)
        except:
            self.vin_line.setText("Please choose a proper vin number")


# Save customer info to database
    def save_customer(self):
        my_db = mysql.connector.connect(

            host="localhost",
            user="root",
            passwd="OpenAuto1",
            database="CUSTOMERS"
        )
        conn = my_db.cursor()

        customers_attributes = (self.name_line.text(), self.address_line.text(), self.city_line.text(),
                                self.state_line.text(), self.zip_line.text(), self.phone_line.text(),
                                self.alt_name.currentText(),self.alt_phone_line.text(),self.email_line.text())
        add_options = """INSERT INTO customers (name, address, city, state, zip, phone, alt_name, alt_phone, email) 
                            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)"""
        conn.execute(add_options, customers_attributes)
        my_db.commit()
        my_db.close()

    def save_vehicle(self):
        my_db = mysql.connector.connect(

            host="localhost",
            user="root",
            passwd="OpenAuto1",
            database="CUSTOMERS"
        )
        conn = my_db.cursor()
        key_id = vehicle_db.find_last_entry_id(self)

        vehicle_attributes = (self.vin_line.text(), self.year_line.text(), self.make_line.text(),
                              self.model_line.text(), self.engine_line.text(), self.trim_line.text(), key_id)
        add_vehicle_options = """ INSERT INTO vehicles ( vin, year, make, model, engine, trim, vehicle_id)
                                       VALUES (%s, %s, %s, %s, %s, %s, %s)"""
        conn.execute(add_vehicle_options, vehicle_attributes)
        my_db.commit()
        my_db.close()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1154, 664)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/car.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.customer_label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.customer_label.setFont(font)
        self.customer_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.customer_label.setObjectName("customer_label")
        self.gridLayout.addWidget(self.customer_label, 0, 0, 1, 1)
        self.vin_label = QtWidgets.QLabel(parent=Form)
        self.vin_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.vin_label.setFont(font)
        self.vin_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.vin_label.setObjectName("vin_label")
        self.gridLayout.addWidget(self.vin_label, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.name_label = QtWidgets.QLabel(parent=Form)
        self.name_label.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout_8.addWidget(self.name_label)
        self.name_line = QtWidgets.QLineEdit(parent=Form)
        self.name_line.setMinimumSize(QtCore.QSize(50, 30))
        self.name_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_line.setObjectName("name_line")
        self.horizontalLayout_8.addWidget(self.name_line)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.address_label = QtWidgets.QLabel(parent=Form)
        self.address_label.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.address_label.setFont(font)
        self.address_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.address_label.setObjectName("address_label")
        self.horizontalLayout_9.addWidget(self.address_label)
        self.address_line = QtWidgets.QLineEdit(parent=Form)
        self.address_line.setMinimumSize(QtCore.QSize(50, 30))
        self.address_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.address_line.setObjectName("address_line")
        self.horizontalLayout_9.addWidget(self.address_line)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.city_label = QtWidgets.QLabel(parent=Form)
        self.city_label.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.city_label.setFont(font)
        self.city_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.city_label.setObjectName("city_label")
        self.horizontalLayout_10.addWidget(self.city_label)
        self.city_line = QtWidgets.QLineEdit(parent=Form)
        self.city_line.setMinimumSize(QtCore.QSize(0, 30))
        self.city_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.city_line.setObjectName("city_line")
        self.horizontalLayout_10.addWidget(self.city_line)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.state_label = QtWidgets.QLabel(parent=Form)
        self.state_label.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.state_label.setFont(font)
        self.state_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.state_label.setObjectName("state_label")
        self.horizontalLayout_11.addWidget(self.state_label)
        self.state_line = QtWidgets.QLineEdit(parent=Form)
        self.state_line.setMinimumSize(QtCore.QSize(0, 30))
        self.state_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.state_line.setObjectName("state_line")
        self.horizontalLayout_11.addWidget(self.state_line)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.zip_label = QtWidgets.QLabel(parent=Form)
        self.zip_label.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.zip_label.setFont(font)
        self.zip_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.zip_label.setObjectName("zip_label")
        self.horizontalLayout_12.addWidget(self.zip_label)
        self.zip_line = QtWidgets.QLineEdit(parent=Form)
        self.zip_line.setMinimumSize(QtCore.QSize(0, 30))
        self.zip_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.zip_line.setObjectName("zip_line")
        self.zip_line.setMaxLength(5)
        self.zip_line.setPlaceholderText("12345")
        self.horizontalLayout_12.addWidget(self.zip_line)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.phone_label = QtWidgets.QLabel(parent=Form)
        self.phone_label.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.phone_label.setFont(font)
        self.phone_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.phone_label.setObjectName("phone_label")
        self.horizontalLayout_13.addWidget(self.phone_label)
        self.phone_line = QtWidgets.QLineEdit(parent=Form)
        self.phone_line.setMinimumSize(QtCore.QSize(0, 30))
        self.phone_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.phone_line.setObjectName("phone_line")
        self.phone_line.setPlaceholderText("(   ) -   -    ")
        self.horizontalLayout_13.addWidget(self.phone_line)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")

        self.alt_phone_label = QtWidgets.QLabel(parent=Form)
        self.alt_phone_label.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.alt_phone_label.setFont(font)
        self.alt_phone_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.alt_phone_label.setObjectName("alt_phone_label")
        self.horizontalLayout_14.addWidget(self.alt_phone_label)
        self.alt_name = QtWidgets.QComboBox(parent=Form)
        self.alt_name.setMinimumSize(150, 0)
        self.alt_name.setObjectName("alt_name")
        self.alt_name.setEditable(True)
        name_items = ["Work", "Cell", "Home", "Relative"]
        self.alt_name.addItems(name_items)
        self.horizontalLayout_14.addWidget(self.alt_name)
        self.alt_phone_line = QtWidgets.QLineEdit(parent=Form)
        self.alt_phone_line.setMinimumSize(QtCore.QSize(0, 30))
        self.alt_phone_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.alt_phone_line.setObjectName("alt_phone_line")
        self.horizontalLayout_14.addWidget(self.alt_phone_line)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.email_label = QtWidgets.QLabel(parent=Form)
        self.email_label.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.email_label.setFont(font)
        self.email_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.email_label.setObjectName("email_label")
        self.horizontalLayout_15.addWidget(self.email_label)
        self.email_line = QtWidgets.QLineEdit(parent=Form)
        self.email_line.setMinimumSize(QtCore.QSize(0, 30))
        self.email_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.email_line.setObjectName("email_line")
        self.horizontalLayout_15.addWidget(self.email_line)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 2, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vin_search_button = QtWidgets.QPushButton(parent=Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.vin_search_button.setIcon(icon1)
        self.vin_search_button.setIconSize(QtCore.QSize(30, 30))
        self.vin_search_button.setFlat(True)
        self.vin_search_button.setObjectName("vin_search_button")
        self.vin_search_button.clicked.connect(self.vin_search)
        self.horizontalLayout_2.addWidget(self.vin_search_button)
        self.vin_line = QtWidgets.QLineEdit(parent=Form)
        self.vin_line.setMinimumSize(QtCore.QSize(0, 35))
        self.vin_line.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.vin_line.setFont(font)
        self.vin_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.vin_line.setObjectName("vin_line")
        self.horizontalLayout_2.addWidget(self.vin_line)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.year_label = QtWidgets.QLabel(parent=Form)
        self.year_label.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.year_label.setFont(font)
        self.year_label.setStyleSheet("text-align: center;")
        self.year_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.year_label.setObjectName("year_label")
        self.horizontalLayout_4.addWidget(self.year_label)
        self.year_line = QtWidgets.QLineEdit(parent=Form)
        self.year_line.setMinimumSize(QtCore.QSize(50, 30))
        self.year_line.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.year_line.setFont(font)
        self.year_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.year_line.setObjectName("year_line")
        self.horizontalLayout_4.addWidget(self.year_line)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.make_label = QtWidgets.QLabel(parent=Form)
        self.make_label.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.make_label.setFont(font)
        self.make_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.make_label.setObjectName("make_label")
        self.horizontalLayout_5.addWidget(self.make_label)
        self.make_line = QtWidgets.QLineEdit(parent=Form)
        self.make_line.setMinimumSize(QtCore.QSize(0, 30))
        self.make_line.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.make_line.setFont(font)
        self.make_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.make_line.setObjectName("make_line")
        self.horizontalLayout_5.addWidget(self.make_line)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.model_label = QtWidgets.QLabel(parent=Form)
        self.model_label.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.model_label.setFont(font)
        self.model_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.model_label.setObjectName("model_label")
        self.horizontalLayout_6.addWidget(self.model_label)
        self.model_line = QtWidgets.QLineEdit(parent=Form)
        self.model_line.setMinimumSize(QtCore.QSize(0, 30))
        self.model_line.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.model_line.setFont(font)
        self.model_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.model_line.setObjectName("model_line")
        self.horizontalLayout_6.addWidget(self.model_line)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.engine_label = QtWidgets.QLabel(parent=Form)
        self.engine_label.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.engine_label.setFont(font)
        self.engine_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.engine_label.setObjectName("engine_label")
        self.horizontalLayout_3.addWidget(self.engine_label)
        self.engine_line = QtWidgets.QLineEdit(parent=Form)
        self.engine_line.setMinimumSize(QtCore.QSize(0, 30))
        self.engine_line.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.engine_line.setFont(font)
        self.engine_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.engine_line.setObjectName("engine_line")
        self.horizontalLayout_3.addWidget(self.engine_line)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.trim_label = QtWidgets.QLabel(parent=Form)
        self.trim_label.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.trim_label.setFont(font)
        self.trim_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.trim_label.setObjectName("trim_label")
        self.horizontalLayout_7.addWidget(self.trim_label)
        self.trim_line = QtWidgets.QLineEdit(parent=Form)
        self.trim_line.setMinimumSize(QtCore.QSize(0, 30))
        self.trim_line.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.trim_line.setFont(font)
        self.trim_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.trim_line.setObjectName("trim_line")
        self.horizontalLayout_7.addWidget(self.trim_line)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.gridLayout.addLayout(self.verticalLayout, 2, 1, 1, 1)
        self.winter_auto_logo = QtWidgets.QLabel(parent=Form)
        self.winter_auto_logo.setMaximumSize(QtCore.QSize(16777215, 200))
        self.winter_auto_logo.setText("")
        self.winter_auto_logo.setPixmap(QtGui.QPixmap("../ui_files/Images/winter_auto.png"))
        self.winter_auto_logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.winter_auto_logo.setObjectName("winter_auto_logo")
        self.gridLayout.addWidget(self.winter_auto_logo, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 150, -1, 9)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.abort_button = QtWidgets.QPushButton(parent=Form)
        self.abort_button.setStyleSheet("text-align: center;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/cross.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.abort_button.setIcon(icon2)
        self.abort_button.setIconSize(QtCore.QSize(30, 30))
        self.abort_button.setAutoRepeatDelay(100)
        self.abort_button.setFlat(True)
        self.abort_button.setObjectName("abort_button")
        self.horizontalLayout.addWidget(self.abort_button)
        self.save_create_button = QtWidgets.QPushButton(parent=Form)
        self.save_create_button.setStyleSheet("text-align: center;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/check.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.save_create_button.setIcon(icon3)
        self.save_create_button.setIconSize(QtCore.QSize(30, 30))
        self.save_create_button.setFlat(True)
        self.save_create_button.setObjectName("save_create_button")
        self.save_create_button.clicked.connect(self.save_customer)
        self.save_create_button.clicked.connect(self.save_vehicle)
        self.save_create_button.clicked.connect(Form.close)
        self.horizontalLayout.addWidget(self.save_create_button)
        self.edit_button = QtWidgets.QPushButton(parent=Form)
        self.edit_button.setStyleSheet("text-align: center;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/check.png"), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.On)
        self.edit_button.setIcon(icon4)
        self.edit_button.setIconSize(QtCore.QSize(30, 30))
        self.edit_button.setFlat(True)
        self.edit_button.clicked.connect(self.save_customer)
        self.edit_button.clicked.connect(Form.close)
        self.horizontalLayout.addWidget(self.edit_button)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Customer Info"))
        self.customer_label.setText(_translate("Form", "Customer"))
        self.vin_label.setText(_translate("Form", "Search By VIN"))
        self.name_label.setText(_translate("Form", "Name"))
        self.address_label.setText(_translate("Form", "Address"))
        self.city_label.setText(_translate("Form", "City"))
        self.state_label.setText(_translate("Form", "State"))
        self.zip_label.setText(_translate("Form", "Zip"))
        self.phone_label.setText(_translate("Form", "Phone"))
        self.alt_phone_label.setText(_translate("Form", "Alt_Phone"))
        self.email_label.setText(_translate("Form", "Email"))
        self.vin_search_button.setText(_translate("Form", "VIN Search"))
        self.year_label.setText(_translate("Form", "Year"))
        self.make_label.setText(_translate("Form", "Make"))
        self.model_label.setText(_translate("Form", "Model"))
        self.engine_label.setText(_translate("Form", "Engine"))
        self.trim_label.setText(_translate("Form", "Trim"))
        self.abort_button.setText(_translate("Form", "Abort"))
        self.save_create_button.setText(_translate("Form", "Save"))
        self.edit_button.setText(_translate("Form", "Save Edit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
