from PyQt6 import QtCore, QtGui, QtWidgets
import ro_hub
import customer_hub
import settings_hub


class Ui_MainWindow(object):

    def open_ro_hub(self):
        self.ro_window = QtWidgets.QWidget()
        self.ro_ui = ro_hub.Ui_ROs()
        self.ro_ui.setupUi(self.ro_window)
        self.ro_window.show()
        self.ro_window.showMaximized()

    def open_customer_hub(self):
        self.customer_window = QtWidgets.QMainWindow()
        self.customer_window.ui = customer_hub.Ui_MainWindow()
        self.customer_window.ui.setupUi(self.customer_window)
        self.customer_window.show()
        self.customer_window.showMaximized()

    def open_settings(self):
        self.settings_window = QtWidgets.QWidget()
        self.settings_ui = settings_hub.Ui_Form()
        self.settings_ui.setupUi(self.settings_window)
        self.settings_window.show()



    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
#        MainWindow.setStyleSheet("background-color: #504F4F;\n"
#"\n"
#"\n"
#"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout_2.setObjectName("formLayout_2")
        self.sidebar_menu = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.sidebar_menu.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.sidebar_menu.setFont(font)
        self.sidebar_menu.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.sidebar_menu.setStyleSheet("background-color: #929191;")
        self.sidebar_menu.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.sidebar_menu.setIconSize(QtCore.QSize(30, 30))
        self.sidebar_menu.setElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.sidebar_menu.setTabsClosable(False)
        self.sidebar_menu.setMovable(False)
        self.sidebar_menu.setTabBarAutoHide(True)
        self.sidebar_menu.setVisible(True)
        self.sidebar_menu.setObjectName("sidebar_menu")
        self.Menu = QtWidgets.QWidget()
        self.Menu.setObjectName("Menu")
        self.formLayout = QtWidgets.QFormLayout(self.Menu)
        self.formLayout.setObjectName("formLayout")
        self.ro_button = QtWidgets.QPushButton(parent=self.Menu)
        self.ro_button.setStyleSheet("text-align: left;\n"
";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/list-check.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ro_button.setIcon(icon)
        self.ro_button.setIconSize(QtCore.QSize(30, 30))
        self.ro_button.setFlat(True)
        self.ro_button.setObjectName("ro_button")
        self.ro_button.clicked.connect(self.open_ro_hub)
        self.ro_button.clicked.connect(MainWindow.close)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.ro_button)
        self.customers_button = QtWidgets.QPushButton(parent=self.Menu)
        self.customers_button.setStyleSheet("text-align: left;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/user.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.customers_button.setIcon(icon1)
        self.customers_button.setIconSize(QtCore.QSize(30, 30))
        self.customers_button.setFlat(True)
        self.customers_button.setObjectName("customers_button")
        self.customers_button.clicked.connect(self.open_customer_hub)
        self.customers_button.clicked.connect(MainWindow.close)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.customers_button)
        self.vehicles_button = QtWidgets.QPushButton(parent=self.Menu)
        self.vehicles_button.setStyleSheet("text-align: left;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/car.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.vehicles_button.setIcon(icon2)
        self.vehicles_button.setIconSize(QtCore.QSize(30, 30))
        self.vehicles_button.setFlat(True)
        self.vehicles_button.setObjectName("vehicles_button")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.vehicles_button)
        self.scheduling_button = QtWidgets.QPushButton(parent=self.Menu)
        self.scheduling_button.setStyleSheet("text-align: left;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/calendar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.scheduling_button.setIcon(icon3)
        self.scheduling_button.setIconSize(QtCore.QSize(30, 30))
        self.scheduling_button.setFlat(True)
        self.scheduling_button.setObjectName("scheduling_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.scheduling_button)
        self.analytics_button = QtWidgets.QPushButton(parent=self.Menu)
        self.analytics_button.setStyleSheet("text-align: left;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/chart-histogram.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.analytics_button.setIcon(icon4)
        self.analytics_button.setIconSize(QtCore.QSize(30, 30))
        self.analytics_button.setFlat(True)
        self.analytics_button.setObjectName("analytics_button")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.analytics_button)
        self.settings_button = QtWidgets.QPushButton(parent=self.Menu)
        self.settings_button.setStyleSheet("text-align: left;")
        self.settings_button.clicked.connect(self.open_settings)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settings_button.setIcon(icon5)
        self.settings_button.setIconSize(QtCore.QSize(30, 30))
        self.settings_button.setFlat(True)
        self.settings_button.setObjectName("settings_button")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.settings_button)
        self.sidebar_menu.addTab(self.Menu, "")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.sidebar_menu)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ro_main_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ro_main_button.setMinimumSize(QtCore.QSize(150, 150))
        self.ro_main_button.setStyleSheet("background-color: #929191;")
        self.ro_main_button.setText("")
        self.ro_main_button.setIcon(icon)
        self.ro_main_button.setIconSize(QtCore.QSize(100, 100))
        self.ro_main_button.setObjectName("ro_main_button")
        self.ro_main_button.clicked.connect(self.open_ro_page)
        self.ro_main_button.clicked.connect(MainWindow.close)
        self.verticalLayout.addWidget(self.ro_main_button)
        self.ro_main_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.ro_main_label.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ro_main_label.setFont(font)
        self.ro_main_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ro_main_label.setObjectName("ro_main_label")
        self.verticalLayout.addWidget(self.ro_main_label)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.customer_main_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.customer_main_button.setMinimumSize(QtCore.QSize(150, 150))
        self.customer_main_button.setStyleSheet("background-color: #929191;")
        self.customer_main_button.setText("")
        self.customer_main_button.setIcon(icon1)
        self.customer_main_button.setIconSize(QtCore.QSize(100, 100))
        self.customer_main_button.setFlat(False)
        self.customer_main_button.setObjectName("customer_main_button")
        self.customer_main_button.clicked.connect(self.open_customer_hub)
        self.customer_main_button.clicked.connect(MainWindow.close)
        self.verticalLayout_2.addWidget(self.customer_main_button)
        self.customer_main_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.customer_main_label.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.customer_main_label.setFont(font)
        self.customer_main_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.customer_main_label.setObjectName("customer_main_label")
        self.verticalLayout_2.addWidget(self.customer_main_label)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.messaging_main_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.messaging_main_button.setMinimumSize(QtCore.QSize(150, 150))
        self.messaging_main_button.setStyleSheet("background-color: #929191;")
        self.messaging_main_button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/comment-alt.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.messaging_main_button.setIcon(icon6)
        self.messaging_main_button.setIconSize(QtCore.QSize(100, 100))
        self.messaging_main_button.setObjectName("messaging_main_button")
        self.verticalLayout_3.addWidget(self.messaging_main_button)
        self.messaging_main_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.messaging_main_label.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.messaging_main_label.setFont(font)
        self.messaging_main_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.messaging_main_label.setObjectName("messaging_main_label")
        self.verticalLayout_3.addWidget(self.messaging_main_label)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scheduling_main_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.scheduling_main_button.setMinimumSize(QtCore.QSize(150, 150))
        self.scheduling_main_button.setStyleSheet("background-color: #929191;")
        self.scheduling_main_button.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/calendar (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.scheduling_main_button.setIcon(icon7)
        self.scheduling_main_button.setIconSize(QtCore.QSize(100, 100))
        self.scheduling_main_button.setObjectName("scheduling_main_button")
        self.verticalLayout_4.addWidget(self.scheduling_main_button)
        self.scheculing_main_button = QtWidgets.QLabel(parent=self.centralwidget)
        self.scheculing_main_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.scheculing_main_button.setFont(font)
        self.scheculing_main_button.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scheculing_main_button.setObjectName("scheculing_main_button")
        self.verticalLayout_4.addWidget(self.scheculing_main_button)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 3, 1, 1)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.gridLayout)
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.formLayout_2.setItem(4, QtWidgets.QFormLayout.ItemRole.LabelRole, spacerItem)
        self.command_help_button = QtWidgets.QCommandLinkButton(parent=self.centralwidget)
        self.command_help_button.setObjectName("command_help_button")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.command_help_button)
        self.toolButton = QtWidgets.QToolButton(parent=self.centralwidget)
        self.toolButton.setStyleSheet("background-color: #504F4F;")
        self.toolButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/menu-burger.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton.setIcon(icon8)
        self.toolButton.setIconSize(QtCore.QSize(30, 30))
        self.toolButton.setObjectName("toolButton")
        self.toolButton.setCheckable(True)
        self.toolButton.clicked.connect(self.tab_hide)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.toolButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.formLayout_2.setItem(2, QtWidgets.QFormLayout.ItemRole.LabelRole, spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.sidebar_menu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def tab_hide(self):
        if self.toolButton.isChecked():
                self.sidebar_menu.setVisible(False)
        else:
            self.sidebar_menu.setVisible(True)

    def open_ro_page(self):
            if self.ro_main_button.clicked:
                    self.open_ro_hub()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Home"))
        self.ro_button.setText(_translate("MainWindow", "Ro\'s"))
        self.customers_button.setText(_translate("MainWindow", "Customers"))
        self.vehicles_button.setText(_translate("MainWindow", "Vehicles"))
        self.scheduling_button.setText(_translate("MainWindow", "Scheduling"))
        self.analytics_button.setText(_translate("MainWindow", "Analytics"))
        self.settings_button.setText(_translate("MainWindow", "Settings"))
        self.sidebar_menu.setTabText(self.sidebar_menu.indexOf(self.Menu), _translate("MainWindow", "Menu"))
        self.ro_main_label.setText(_translate("MainWindow", "RO\'s"))
        self.customer_main_label.setText(_translate("MainWindow", "Customers"))
        self.messaging_main_label.setText(_translate("MainWindow", "Messaging"))
        self.scheculing_main_button.setText(_translate("MainWindow", "Scheduling"))
        self.command_help_button.setText(_translate("MainWindow", "Click here for Help and FAQ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
