from PyQt6 import QtCore, QtGui, QtWidgets
import sys
import home
import time

class Ui_MainWindow(object):

    def open_home_page(self):
        self.show_home_page = QtWidgets.QMainWindow()
        self.home_page_ui = home.Ui_MainWindow()
        self.home_page_ui.setupUi(self.show_home_page)
        self.show_home_page.show()
        self.show_home_page.showMaximized()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("LoginWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
#        MainWindow.setStyleSheet("  background-color: #504F4F;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.help_link_button = QtWidgets.QCommandLinkButton(parent=self.centralwidget)
        self.help_link_button.setMinimumSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.help_link_button.setFont(font)
        self.help_link_button.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.help_link_button.setStyleSheet("text-align: center;")
        self.help_link_button.setObjectName("help_link_button")
        self.gridLayout_3.addWidget(self.help_link_button, 0, 0, 1, 1)
        self.login_create_tab = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.login_create_tab.setStyleSheet("background-color: #6A6869;")
        self.login_create_tab.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.login_create_tab.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.login_create_tab.setTabBarAutoHide(False)
        self.login_create_tab.setObjectName("login_create_tab")
        self.Login = QtWidgets.QWidget()
        self.Login.setObjectName("Login")
        self.gridLayout = QtWidgets.QGridLayout(self.Login)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.remember_login_checkbox = QtWidgets.QCheckBox(parent=self.Login)
        self.remember_login_checkbox.setObjectName("remember_login_checkbox")
        self.horizontalLayout_2.addWidget(self.remember_login_checkbox)
        self.login_abort_button = QtWidgets.QPushButton(parent=self.Login)
        self.login_abort_button.setMinimumSize(QtCore.QSize(0, 30))
        self.login_abort_button.setStyleSheet("background-color: #DE3163;")
        self.login_abort_button.setIconSize(QtCore.QSize(16, 16))
        self.login_abort_button.setObjectName("login_abort_button")
        self.login_abort_button.clicked.connect(sys.exit)
        self.horizontalLayout_2.addWidget(self.login_abort_button)
        self.login_button_ok = QtWidgets.QPushButton(parent=self.Login)
        self.login_button_ok.setMinimumSize(QtCore.QSize(0, 30))
        self.login_button_ok.setStyleSheet("background-color: #929191;")
        self.login_button_ok.setObjectName("login_button_ok")
        self.login_button_ok.clicked.connect(self.open_home_page)
        self.login_button_ok.clicked.connect(MainWindow.close)
        self.horizontalLayout_2.addWidget(self.login_button_ok)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.user_login_label = QtWidgets.QLabel(parent=self.Login)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.user_login_label.setFont(font)
        self.user_login_label.setAutoFillBackground(False)
        self.user_login_label.setStyleSheet("text-align: center;")
        self.user_login_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.user_login_label.setObjectName("user_login_label")
        self.verticalLayout_2.addWidget(self.user_login_label)
        self.user_login_line_edit = QtWidgets.QLineEdit(parent=self.Login)
        self.user_login_line_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.user_login_line_edit.setStyleSheet("background-color: #FAF7F7;\n"
"color: black;")
        self.user_login_line_edit.setText("")
        self.user_login_line_edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.user_login_line_edit.setObjectName("user_login_line_edit")
        self.verticalLayout_2.addWidget(self.user_login_line_edit)
        self.pass_login_label = QtWidgets.QLabel(parent=self.Login)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.pass_login_label.setFont(font)
        self.pass_login_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pass_login_label.setObjectName("pass_login_label")
        self.verticalLayout_2.addWidget(self.pass_login_label)
        self.pass_login_line_edit = QtWidgets.QLineEdit(parent=self.Login)
        self.pass_login_line_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.pass_login_line_edit.setStyleSheet("background-color: #FAF7F7;\n"
"color: black;")
        self.pass_login_line_edit.setText("")
        self.pass_login_line_edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pass_login_line_edit.setObjectName("pass_login_line_edit")
        self.pass_login_line_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.verticalLayout_2.addWidget(self.pass_login_line_edit)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 30, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.login_create_tab.addTab(self.Login, "")
        self.Create = QtWidgets.QWidget()
        self.Create.setObjectName("Create")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Create)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.user_create_label = QtWidgets.QLabel(parent=self.Create)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.user_create_label.setFont(font)
        self.user_create_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.user_create_label.setObjectName("user_create_label")
        self.verticalLayout.addWidget(self.user_create_label)
        self.user_create_line_edit = QtWidgets.QLineEdit(parent=self.Create)
        self.user_create_line_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.user_create_line_edit.setStyleSheet("background-color: #FAF7F7;\n"
"color: black;")
        self.user_create_line_edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.user_create_line_edit.setObjectName("user_create_line_edit")
        self.verticalLayout.addWidget(self.user_create_line_edit)
        self.pass_create_label = QtWidgets.QLabel(parent=self.Create)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.pass_create_label.setFont(font)
        self.pass_create_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pass_create_label.setObjectName("pass_create_label")
        self.verticalLayout.addWidget(self.pass_create_label)
        self.pass_create_line_edit = QtWidgets.QLineEdit(parent=self.Create)
        self.pass_create_line_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.pass_create_line_edit.setStyleSheet("background-color: #FAF7F7;\n"
"color: black;")
        self.pass_create_line_edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pass_create_line_edit.setObjectName("pass_create_line_edit")
        self.pass_create_line_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.verticalLayout.addWidget(self.pass_create_line_edit)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.writer_create_checkbox = QtWidgets.QCheckBox(parent=self.Create)
        self.writer_create_checkbox.setObjectName("writer_create_checkbox")
        self.horizontalLayout.addWidget(self.writer_create_checkbox)
        self.tech_create_checkbox = QtWidgets.QCheckBox(parent=self.Create)
        self.tech_create_checkbox.setObjectName("tech_create_checkbox")
        self.horizontalLayout.addWidget(self.tech_create_checkbox)
        self.create_abort_button = QtWidgets.QPushButton(parent=self.Create)
        self.create_abort_button.setMinimumSize(QtCore.QSize(0, 30))
        self.create_abort_button.setStyleSheet("background-color: #DE3163;")
        self.create_abort_button.setObjectName("create_abort_button")
        self.create_abort_button.clicked.connect(sys.exit)
        self.horizontalLayout.addWidget(self.create_abort_button)
        self.create_ok_button = QtWidgets.QPushButton(parent=self.Create)
        self.create_ok_button.setMinimumSize(QtCore.QSize(0, 30))
        self.create_ok_button.setStyleSheet("background-color: #9FE2BF;")
        self.create_ok_button.setObjectName("create_ok_button")
        self.horizontalLayout.addWidget(self.create_ok_button)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 30, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.login_create_tab.addTab(self.Create, "")
        self.gridLayout_3.addWidget(self.login_create_tab, 0, 1, 3, 1)
        spacerItem2 = QtWidgets.QSpacerItem(442, 150, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setStyleSheet("border-image: url(:/ui_files/Images/winter_auto.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.login_create_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("LoginWindow", "Login/Create"))
        self.help_link_button.setText(_translate("LoginWindow", "Click Here For Website FAQ and Help"))
        self.remember_login_checkbox.setText(_translate("LoginWindow", "Remember Me"))
        self.login_abort_button.setText(_translate("LoginWindow", "Abort"))
        self.login_button_ok.setText(_translate("LoginWindow", "OK"))
        self.user_login_label.setText(_translate("LoginWindow", "USERNAME"))
        self.pass_login_label.setText(_translate("LoginWindow", "PASSWORD"))
        self.login_create_tab.setTabText(self.login_create_tab.indexOf(self.Login), _translate("LoginWindow", "Login"))
        self.user_create_label.setText(_translate("LoginWindow", "USERNAME"))
        self.pass_create_label.setText(_translate("LoginWindow", "PASSWORD"))
        self.writer_create_checkbox.setText(_translate("LoginWindow", "Writer"))
        self.tech_create_checkbox.setText(_translate("LoginWindow", "Tech"))
        self.create_abort_button.setText(_translate("LoginWindow", "Abort"))
        self.create_ok_button.setText(_translate("LoginWindow", "OK"))
        self.login_create_tab.setTabText(self.login_create_tab.indexOf(self.Create), _translate("LoginWindow", "Create"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
