from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector

class Ui_MainWindow(object):
    def highlight_items(self):
        self.activity_table.model()
        row = self.activity_table.currentRow()
        self.activity_table.selectRow(row)


    def delete_row_item(self):
        highlight_jobs = self.activity_table.model()
        selected_row = self.activity_table.currentRow()
        self.activity_table.removeRow(selected_row)


    def change_lines(self):
        if self.part_labor_box.currentIndex() == 1:
            self.sell_line.hide()
            self.pushButton.hide()
            self.cost_label.setText("Labor Rate")
            self.cost_line.setText("125")
        elif self.part_labor_box.currentIndex() == 0:
            self.sell_line.show()
            self.pushButton.show()
            self.cost_label.setText("$ Cost")
            self.cost_line.clear()
        elif self.part_labor_box.currentIndex() == 2:
            self.sell_line.hide()
            self.pushButton.hide()
            self.cost_label.setText("$ Cost")
            self.cost_line.clear()

    def add_line_items(self):
        row_count = self.activity_table.rowCount()
        job_items = (
        self.job_line_edit.text(), self.cost_line.text(), self.sell_line.text(), self.amount_line.text(),
        self.total_line.text(), self.discount_line.text())
        add_jobs = self.activity_table.model()
        if self.part_labor_box.currentIndex() == 0:
            add_jobs.insertRow(row_count)
            self.activity_table.setItem(row_count, 0, QtWidgets.QTableWidgetItem("(Part)  " + job_items[0]))
            self.activity_table.setItem(row_count, 1, QtWidgets.QTableWidgetItem(job_items[1]))
            self.activity_table.setItem(row_count, 2, QtWidgets.QTableWidgetItem(job_items[2]))
            self.activity_table.setItem(row_count, 3, QtWidgets.QTableWidgetItem(job_items[3]))
            self.activity_table.setItem(row_count, 4, QtWidgets.QTableWidgetItem(job_items[4]))
            self.activity_table.setItem(row_count, 5, QtWidgets.QTableWidgetItem(job_items[5]))
            self.activity_table.setItem(row_count, 6, QtWidgets.QTableWidgetItem(str(self.part_labor_box.currentIndex())))
            self.job_line_edit.clear()
            self.cost_line.clear()
            self.sell_line.clear()
            self.amount_line.clear()
            self.total_line.clear()
            self.discount_line.clear()
        elif self.part_labor_box.currentIndex() == 1:
            add_jobs.insertRow(row_count)
            self.activity_table.setItem(row_count, 0, QtWidgets.QTableWidgetItem("(Labor) " + job_items[0]))
            self.activity_table.setItem(row_count, 1, QtWidgets.QTableWidgetItem(job_items[1]))
            self.activity_table.setItem(row_count, 3, QtWidgets.QTableWidgetItem(job_items[3]))
            self.activity_table.setItem(row_count, 4, QtWidgets.QTableWidgetItem(job_items[4]))
            self.activity_table.setItem(row_count, 5, QtWidgets.QTableWidgetItem(job_items[5]))
        elif self.part_labor_box.currentIndex() == 2:
            add_jobs.insertRow(row_count)
            self.activity_table.setItem(row_count, 0, QtWidgets.QTableWidgetItem("(Fee) " + job_items[0]))

    def concern_write(self):
        self.cause_edit.hide()
        self.correction_edit.hide()
        self.concern_edit.show()

    def cause_write(self):
        self.concern_edit.hide()
        self.correction_edit.hide()
        self.cause_edit.show()

    def correction_write(self):
        self.concern_edit.hide()
        self.cause_edit.hide()
        self.correction_edit.show()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1421, 896)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 48))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/document.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.job_line_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.job_line_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.job_line_label.setObjectName("job_line_label")
        self.verticalLayout.addWidget(self.job_line_label)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.part_labor_box = QtWidgets.QComboBox(parent=self.centralwidget)
        self.part_labor_box.setObjectName("part_labor_box")
        box_items = ["Part", "Labor", "Fee"]
        self.part_labor_box.addItems(box_items)
        self.part_labor_box.currentIndexChanged.connect(self.change_lines)
        self.horizontalLayout_16.addWidget(self.part_labor_box)
        self.job_line_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.job_line_edit.setMinimumSize(QtCore.QSize(400, 0))
        self.job_line_edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.job_line_edit.setObjectName("job_line_edit")
        self.horizontalLayout_16.addWidget(self.job_line_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cost_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.cost_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cost_label.setObjectName("cost_label")
        self.verticalLayout_3.addWidget(self.cost_label)
        self.cost_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.cost_line.setMinimumSize(QtCore.QSize(0, 0))
        self.cost_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cost_line.setObjectName("cost_line")
        self.verticalLayout_3.addWidget(self.cost_line)
        self.horizontalLayout_17.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 55))
        self.pushButton.setStyleSheet("text-decoration: underline;\n" "color: red;")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        self.sell_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.sell_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sell_line.setObjectName("sell_line")
        self.verticalLayout_5.addWidget(self.sell_line)
        self.horizontalLayout_17.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.amount_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.amount_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.amount_label.setObjectName("amount_label")
        self.verticalLayout_6.addWidget(self.amount_label)
        self.amount_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.amount_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.amount_line.setObjectName("amount_line")
        self.verticalLayout_6.addWidget(self.amount_line)
        self.horizontalLayout_17.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.total_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.total_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.total_label.setObjectName("total_label")
        self.verticalLayout_7.addWidget(self.total_label)
        self.total_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.total_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.total_line.setObjectName("total_line")
        self.verticalLayout_7.addWidget(self.total_line)
        self.horizontalLayout_17.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.discount_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.discount_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.discount_label.setObjectName("discount_label")
        self.verticalLayout_8.addWidget(self.discount_label)
        self.discount_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.discount_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.discount_line.setObjectName("discount_line")
        self.verticalLayout_8.addWidget(self.discount_line)
        self.horizontalLayout_17.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.add_line_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.add_line_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.add_line_label.setObjectName("add_line_label")
        self.verticalLayout_9.addWidget(self.add_line_label)
        self.add_update_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_update_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/list-check.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_update_button.setIcon(icon1)
        self.add_update_button.setIconSize(QtCore.QSize(30, 30))
        self.add_update_button.setFlat(True)
        self.add_update_button.clicked.connect(self.add_line_items)
        self.add_update_button.setObjectName("add_update_button")
        self.verticalLayout_9.addWidget(self.add_update_button)
        self.horizontalLayout_17.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.delete_line_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.delete_line_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.delete_line_label.setObjectName("delete_line_label")
        self.verticalLayout_10.addWidget(self.delete_line_label)
        self.delete_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delete_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/trash.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.delete_button.setIcon(icon2)
        self.delete_button.setIconSize(QtCore.QSize(30, 30))
        self.delete_button.setFlat(True)
        self.delete_button.setObjectName("delete_button")
        self.delete_button.clicked.connect(self.delete_row_item)
        self.verticalLayout_10.addWidget(self.delete_button)
        self.horizontalLayout_17.addLayout(self.verticalLayout_10)
        self.gridLayout.addLayout(self.horizontalLayout_17, 3, 0, 1, 7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.vin_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.vin_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.vin_label.setObjectName("vin_label")
        self.horizontalLayout_5.addWidget(self.vin_label)
        self.vin_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.vin_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.vin_line.setObjectName("vin_line")
        self.vin_line.setEnabled(False)
        self.horizontalLayout_5.addWidget(self.vin_line)
        self.vin_copy_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.vin_copy_button.setMaximumSize(QtCore.QSize(100, 16777215))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/edit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.vin_copy_button.setIcon(icon3)
        self.vin_copy_button.setObjectName("vin_copy_button")
        self.horizontalLayout_5.addWidget(self.vin_copy_button)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 2)
        self.cause_edit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.cause_edit.setObjectName("cause_edit")
        self.gridLayout.addWidget(self.cause_edit, 9, 5, 3, 3)
        self.logo_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("../ui_files/Images/winter_auto.png"))
        self.logo_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logo_label.setObjectName("logo_label")
        self.gridLayout.addWidget(self.logo_label, 9, 2, 3, 1)
        spacerItem = QtWidgets.QSpacerItem(370, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.year_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.year_label.setObjectName("year_label")
        self.horizontalLayout_6.addWidget(self.year_label)
        self.year_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.year_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.year_line.setObjectName("year_line")
        self.year_line.setEnabled(False)
        self.horizontalLayout_6.addWidget(self.year_line)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.make_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.make_label.setObjectName("make_label")
        self.horizontalLayout_7.addWidget(self.make_label)
        self.make_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.make_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.make_line.setObjectName("make_line")
        self.make_line.setEnabled(False)
        self.horizontalLayout_7.addWidget(self.make_line)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.model_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.model_label.setObjectName("model_label")
        self.horizontalLayout_10.addWidget(self.model_label)
        self.model_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.model_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.model_line.setObjectName("model_line")
        self.model_line.setEnabled(False)
        self.horizontalLayout_10.addWidget(self.model_line)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.engine_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.engine_label.setObjectName("engine_label")
        self.horizontalLayout_11.addWidget(self.engine_label)
        self.engine_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.engine_line.sizePolicy().hasHeightForWidth())
        self.engine_line.setSizePolicy(sizePolicy)
        self.engine_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.engine_line.setObjectName("engine_line")
        self.engine_line.setEnabled(False)
        self.horizontalLayout_11.addWidget(self.engine_line)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 2)
        self.concern_edit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.concern_edit.setObjectName("concern_edit")
        self.gridLayout.addWidget(self.concern_edit, 9, 5, 3, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 164, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 3, 3, 1)
        self.parts_order_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.parts_order_button.setMaximumSize(QtCore.QSize(251, 50))
        self.parts_order_button.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.parts_order_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/partstech_logo.jpeg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.parts_order_button.setIcon(icon4)
        self.parts_order_button.setIconSize(QtCore.QSize(200, 200))
        self.parts_order_button.setFlat(False)
        self.parts_order_button.setObjectName("parts_order_button")
        self.gridLayout.addWidget(self.parts_order_button, 3, 7, 1, 1)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout.addWidget(self.name_label)
        self.name_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name_line.setMinimumSize(QtCore.QSize(143, 0))
        self.name_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_line.setObjectName("name_line")
        self.name_line.setEnabled(False)
        self.horizontalLayout.addWidget(self.name_line)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.phone_label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.phone_label.setFont(font)
        self.phone_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.phone_label.setObjectName("phone_label")
        self.horizontalLayout_2.addWidget(self.phone_label)
        self.phone_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.phone_line.setMinimumSize(QtCore.QSize(143, 0))
        self.phone_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.phone_line.setObjectName("phone_line")
        self.phone_line.setEnabled(False)
        self.horizontalLayout_2.addWidget(self.phone_line)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.alt_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.alt_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.alt_label.setObjectName("alt_label")
        self.horizontalLayout_3.addWidget(self.alt_label)
        self.alt_phone_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alt_phone_line.sizePolicy().hasHeightForWidth())
        self.alt_phone_line.setSizePolicy(sizePolicy)
        self.alt_phone_line.setMinimumSize(QtCore.QSize(143, 0))
        self.alt_phone_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.alt_phone_line.setObjectName("alt_phone_line")
        self.alt_phone_line.setEnabled(False)
        self.horizontalLayout_3.addWidget(self.alt_phone_line)
        self.verticalLayout_13.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.email_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.email_label.setObjectName("email_label")
        self.horizontalLayout_4.addWidget(self.email_label)
        self.email_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.email_line.setMinimumSize(QtCore.QSize(143, 0))
        self.email_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.email_line.setObjectName("email_line")
        self.email_line.setEnabled(False)
        self.horizontalLayout_4.addWidget(self.email_line)
        self.verticalLayout_13.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_30.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_14.addWidget(self.label_3)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.created_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.created_label.setObjectName("created_label")
        self.horizontalLayout_26.addWidget(self.created_label)
        self.created_edit = QtWidgets.QDateTimeEdit(parent=self.centralwidget)
        self.created_edit.setObjectName("created_edit")
        self.created_edit.setEnabled(False)
        self.created_edit.setDate(QtCore.QDate.currentDate())

        self.horizontalLayout_26.addWidget(self.created_edit)
        self.verticalLayout_14.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.approved_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.approved_label.setObjectName("approved_label")
        self.horizontalLayout_27.addWidget(self.approved_label)
        self.approved_edit = QtWidgets.QDateTimeEdit(parent=self.centralwidget)
        self.approved_edit.setObjectName("approved_edit")
        self.approved_edit.setEnabled(False)
        self.approved_edit.setDate(QtCore.QDate.currentDate())
        self.horizontalLayout_27.addWidget(self.approved_edit)
        self.verticalLayout_14.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_30.addLayout(self.verticalLayout_14)
        self.gridLayout.addLayout(self.horizontalLayout_30, 0, 4, 3, 4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.miles_in_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.miles_in_line.setMaximumSize(QtCore.QSize(142, 16777215))
        self.miles_in_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.miles_in_line.setObjectName("lineEdit")
        self.horizontalLayout_14.addWidget(self.miles_in_line)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_14.addWidget(self.label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.miles_out_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.miles_out_edit.setMaximumSize(QtCore.QSize(142, 16777215))
        self.miles_out_edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.miles_out_edit.setObjectName("lineEdit_2")
        self.horizontalLayout_15.addWidget(self.miles_out_edit)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_15.addWidget(self.label_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.gridLayout.addLayout(self.verticalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.print_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.print_button.setMinimumSize(QtCore.QSize(0, 36))
        self.print_button.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.print_button.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/print.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.print_button.setIcon(icon5)
        self.print_button.setIconSize(QtCore.QSize(30, 30))
        self.print_button.setFlat(True)
        self.print_button.setObjectName("print_button")
        self.horizontalLayout_8.addWidget(self.print_button)
        self.abort_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.abort_button.setMinimumSize(QtCore.QSize(0, 36))
        self.abort_button.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.abort_button.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/cross.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.abort_button.setIcon(icon6)
        self.abort_button.setIconSize(QtCore.QSize(30, 30))
        self.abort_button.setFlat(True)
        self.abort_button.setObjectName("abort_button")
        self.horizontalLayout_8.addWidget(self.abort_button)
        self.save_button = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setMinimumSize(QtCore.QSize(0, 36))
        self.save_button.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.save_button.setFont(font)
        self.save_button.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/check.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.save_button.setIcon(icon7)
        self.save_button.setIconSize(QtCore.QSize(30, 30))
        self.save_button.setFlat(True)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_8.addWidget(self.save_button)
        self.gridLayout.addLayout(self.horizontalLayout_8, 11, 0, 1, 2)
        self.correction_edit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.correction_edit.setObjectName("correction_edit")
        self.gridLayout.addWidget(self.correction_edit, 9, 5, 3, 3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.concern_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.concern_button.setMaximumSize(QtCore.QSize(16777215, 36))
        self.concern_button.setObjectName("concern_button")
        self.concern_button.toggled.connect(self.concern_write)
        self.concern_button.setChecked(True)
        self.horizontalLayout_9.addWidget(self.concern_button)
        self.cause_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.cause_button.setMaximumSize(QtCore.QSize(16777215, 36))
        self.cause_button.setObjectName("cause_button")
        self.cause_button.toggled.connect(self.cause_write)
        self.horizontalLayout_9.addWidget(self.cause_button)
        self.correction_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.correction_button.setMaximumSize(QtCore.QSize(16777215, 36))
        self.correction_button.setObjectName("correction_button")
        self.correction_button.toggled.connect(self.correction_write)
        self.horizontalLayout_9.addWidget(self.correction_button)
        self.gridLayout.addLayout(self.horizontalLayout_9, 7, 6, 1, 2)
        self.activity_table = QtWidgets.QTableWidget(parent=self.centralwidget)
       # self.activity_table.setMinimumSize(QtCore.QSize(0, 200))
        self.activity_table.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.activity_table.setGridStyle(QtCore.Qt.PenStyle.DotLine)
        self.activity_table.setColumnCount(7)
        self.activity_table.setEditTriggers(QtWidgets.QTableWidget.EditTrigger.NoEditTriggers)
        header_names = ("Type", "Cost", "Sell", "Amount", "Total", "Discount", "ID")
      #  self.activity_table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.activity_table.setObjectName("activity_table")
        self.activity_table.setHorizontalHeaderLabels(header_names)
        header = self.activity_table.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeMode.Stretch)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeMode.Stretch)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeMode.Stretch)
        header.setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        header.setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeMode.Stretch)
        header.setSectionResizeMode(5, QtWidgets.QHeaderView.ResizeMode.Stretch)
        header.setSectionResizeMode(6, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.activity_table.cellClicked.connect(self.highlight_items)
        self.gridLayout.addWidget(self.activity_table, 4, 0, 1, 8)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.parts_total_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.parts_total_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.parts_total_label.setObjectName("parts_total_label")
        self.horizontalLayout_18.addWidget(self.parts_total_label)
        self.parts_total_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.parts_total_line.setMaximumSize(QtCore.QSize(140, 16777215))
        self.parts_total_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.parts_total_line.setObjectName("parts_total_line")
        self.parts_total_line.setEnabled(False)
        self.horizontalLayout_18.addWidget(self.parts_total_line)
        self.verticalLayout_11.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.labor_total_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.labor_total_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labor_total_label.setObjectName("labor_total_label")
        self.horizontalLayout_19.addWidget(self.labor_total_label)
        self.labor_total_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.labor_total_line.setMaximumSize(QtCore.QSize(140, 16777215))
        self.labor_total_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labor_total_line.setObjectName("labor_total_line")
        self.labor_total_line.setEnabled(False)
        self.horizontalLayout_19.addWidget(self.labor_total_line)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.sublet_total_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.sublet_total_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sublet_total_label.setObjectName("sublet_total_label")
        self.horizontalLayout_20.addWidget(self.sublet_total_label)
        self.sublet_total_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.sublet_total_line.setMaximumSize(QtCore.QSize(140, 16777215))
        self.sublet_total_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sublet_total_line.setObjectName("sublet_total_line")
        self.sublet_total_line.setEnabled(False)
        self.horizontalLayout_20.addWidget(self.sublet_total_line)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.sub_total_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.sub_total_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sub_total_label.setObjectName("sub_total_label")
        self.horizontalLayout_21.addWidget(self.sub_total_label)
        self.sub_total_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.sub_total_line.setMaximumSize(QtCore.QSize(140, 16777215))
        self.sub_total_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sub_total_line.setObjectName("sub_total_line")
        self.sub_total_line.setEnabled(False)
        self.horizontalLayout_21.addWidget(self.sub_total_line)
        self.verticalLayout_11.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_29.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.fees_total_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.fees_total_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.fees_total_label.setObjectName("fees_total_label")
        self.horizontalLayout_22.addWidget(self.fees_total_label)
        self.fees_total_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.fees_total_line.setMaximumSize(QtCore.QSize(140, 16777215))
        self.fees_total_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.fees_total_line.setObjectName("fees_total_line")
        self.fees_total_line.setEnabled(False)
        self.horizontalLayout_22.addWidget(self.fees_total_line)
        self.verticalLayout_12.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.EPA_total_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.EPA_total_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.EPA_total_label.setObjectName("EPA_total_label")
        self.horizontalLayout_23.addWidget(self.EPA_total_label)
        self.EPA_total_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.EPA_total_line.setMaximumSize(QtCore.QSize(140, 16777215))
        self.EPA_total_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.EPA_total_line.setObjectName("EPA_total_line")
        self.EPA_total_line.setEnabled(False)
        self.horizontalLayout_23.addWidget(self.EPA_total_line)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.shop_supplies_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.shop_supplies_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.shop_supplies_label.setObjectName("shop_supplies_label")
        self.horizontalLayout_24.addWidget(self.shop_supplies_label)
        self.shop_supplies_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.shop_supplies_line.setMaximumSize(QtCore.QSize(140, 16777215))
        self.shop_supplies_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.shop_supplies_line.setObjectName("shop_supplies_line")
        self.horizontalLayout_24.addWidget(self.shop_supplies_line)
        self.verticalLayout_12.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.tax_total_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.tax_total_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tax_total_label.setObjectName("tax_total_label")
        self.horizontalLayout_25.addWidget(self.tax_total_label)
        self.tax_total_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tax_total_line.setMaximumSize(QtCore.QSize(140, 16777215))
        self.tax_total_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tax_total_line.setObjectName("tax_total_line")
        self.tax_total_line.setEnabled(False)
        self.horizontalLayout_25.addWidget(self.tax_total_line)
        self.verticalLayout_12.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.total_label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.total_label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.total_label_2.setObjectName("total_label_2")
        self.horizontalLayout_28.addWidget(self.total_label_2)
        self.total_checkout_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.total_checkout_line.setMinimumSize(QtCore.QSize(0, 0))
        self.total_checkout_line.setMaximumSize(QtCore.QSize(140, 16777215))
        self.total_checkout_line.setObjectName("lineEdit_3")
        self.total_checkout_line.setEnabled(False)
        self.total_checkout_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayout_28.addWidget(self.total_checkout_line)
        self.verticalLayout_12.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29.addLayout(self.verticalLayout_12)
        self.gridLayout.addLayout(self.horizontalLayout_29, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(570, 135, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 0, 4, 2)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.mpi_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mpi_button.setIcon(icon1)
        self.mpi_button.setIconSize(QtCore.QSize(30, 30))
        self.mpi_button.setFlat(True)
        self.mpi_button.setObjectName("mpi_button")
        self.horizontalLayout_31.addWidget(self.mpi_button)
        self.profit_loss_button = QtWidgets.QPushButton(parent=self.centralwidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../ui_files/Images/Icons/chart-histogram.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.profit_loss_button.setIcon(icon8)
        self.profit_loss_button.setIconSize(QtCore.QSize(30, 30))
        self.profit_loss_button.setFlat(True)
        self.profit_loss_button.setObjectName("profit_loss_button")
        self.horizontalLayout_31.addWidget(self.profit_loss_button)
        self.gridLayout.addLayout(self.horizontalLayout_31, 6, 7, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "REPAIR ORDER"))
        self.job_line_label.setText(_translate("MainWindow", "Description"))
        self.cost_label.setText(_translate("MainWindow", "$ Cost"))
        self.pushButton.setText(_translate("MainWindow", "$ Sell"))
        self.amount_label.setText(_translate("MainWindow", "Amount"))
        self.total_label.setText(_translate("MainWindow", "Total"))
        self.discount_label.setText(_translate("MainWindow", "Discount"))
        self.add_line_label.setText(_translate("MainWindow", "Add"))
        self.delete_line_label.setText(_translate("MainWindow", "Delete"))
        self.vin_label.setText(_translate("MainWindow", "VIN     "))
        self.vin_copy_button.setText(_translate("MainWindow", "Copy"))
        self.year_label.setText(_translate("MainWindow", "Year    "))
        self.make_label.setText(_translate("MainWindow", "Make   "))
        self.model_label.setText(_translate("MainWindow", "Model"))
        self.engine_label.setText(_translate("MainWindow", "Engine"))
        self.name_label.setText(_translate("MainWindow", "Name "))
        self.phone_label.setText(_translate("MainWindow", "Phone"))
        self.alt_label.setText(_translate("MainWindow", "Alt       "))
        self.email_label.setText(_translate("MainWindow", "Email  "))
        self.label_3.setText(_translate("MainWindow", "RO #"))
        self.created_label.setText(_translate("MainWindow", "Created"))
        self.approved_label.setText(_translate("MainWindow", "Approved"))
        self.label.setText(_translate("MainWindow", "Miles-IN     "))
        self.label_2.setText(_translate("MainWindow", "Miles-OUT"))
        self.print_button.setText(_translate("MainWindow", "Print"))
        self.abort_button.setText(_translate("MainWindow", "Abort"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.concern_button.setText(_translate("MainWindow", "Concern"))
        self.cause_button.setText(_translate("MainWindow", "Cause"))
        self.correction_button.setText(_translate("MainWindow", "Correction"))
        self.parts_total_label.setText(_translate("MainWindow", "Parts"))
        self.labor_total_label.setText(_translate("MainWindow", "Labor"))
        self.sublet_total_label.setText(_translate("MainWindow", "Sublet"))
        self.sub_total_label.setText(_translate("MainWindow", "Sub_Total"))
        self.fees_total_label.setText(_translate("MainWindow", "Fees"))
        self.EPA_total_label.setText(_translate("MainWindow", "Epa_Charges"))
        self.shop_supplies_label.setText(_translate("MainWindow", "ShopSupplies"))
        self.tax_total_label.setText(_translate("MainWindow", "TAX"))
        self.total_label_2.setText(_translate("MainWindow", "TOTAL"))
        self.mpi_button.setText(_translate("MainWindow", "MPI"))
        self.profit_loss_button.setText(_translate("MainWindow", " Profit and Loss"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
